version: '3.7'

volumes:
  redis: {}
  quake-data: {}

services:
  redis:
    image: redis:latest
    volumes:
    - redis:/data
    networks:
    - quake-network

  quake-minqlx:
    image: quake-test2
    ports:
    - 27960:27960
    environment:
      SERVER_HOSTNAME:
      SERVER_PASSWORD:
      STEAM_ID:
      RCON_PASSWORD:
      STATS_PASSWORD:
    volumes:
    - quake-data:/Steam/steamapps/common/qlds
    restart: always
    networks:
    - quake-network

networks:
  quake-network:
    driver: bridge

